# Site settings
title: Reid H Lewis
email: reidhlewis91@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A place on the web about the environment, quality of life, technology, and whatever else comes up.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.reidhlewis.com" # the base hostname & protocol for your site
github_username:  ReidasaurusRex
permalink: /blog/:title
# Build settings
markdown: kramdown
author: Reid H Lewis
